# Generated by Django 3.2.7 on 2021-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210917_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
