# Generated by Django 3.2.7 on 2021-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210917_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(related_name='book_countries', to='book.Country'),
        ),
    ]
